

# Using CircleCI 2
version: 2

jobs: 
  build:
    docker: 
      # https://hub.docker.com/r/circleci/node/
      - image: circleci/node
    steps: 
      - checkout
      - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
      - restore_cache:
        key: learnzone-react-dependencies-{{ checksum "package.json" }}
      - run:
        name: install-npm-wee
        command: npm install
      - save_cache:
        key: learnzone-react-dependencies-{{ checksum "package.json" }}
        paths:
          - ./node_modules