

# Using CircleCI 2
version: 2

jobs: 
  build:
    docker: 
      - image: circleci/node
    steps: 
      - checkout
      - run:
        name: update-npm
        command: 'sudo npm install -g npm@latest'
      - restore_cache:
        key: dependencies-{{ checksum "package.json" }}
      - run:
        name: install-npm
        command: npm install
      - save_chace:
        key: dependencies-{{ checksum "package.json" }}
        paths:
          - ./node_modules