# [28-Nov-2018] switch to Yarn
#               https://circleci.com/docs/2.0/yarn/

# Using CircleCI 2
version: 2

# Workflow
workflows:
  version: 2
  full-flow:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          # filters:
          #   branches:
          #     only:
          #       - master

# Jobs
jobs:
  # ---------- Building job
  build:
    docker:
      # https://hub.docker.com/r/circleci/node/
      - image: circleci/node:11-browsers-legacy
    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - learnzone-react-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          # https://yarnpkg.com/lang/en/docs/cli/install/
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: learnzone-react-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  # ---------- Testing job
  test:
    docker:
      # https://hub.docker.com/r/circleci/node/
      - image: circleci/node:11-browsers-legacy
    steps:
      - checkout
      # Cache should not have changed as "build" ran before. Just get it back
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - learnzone-react-dependencies-{{ checksum "yarn.lock" }}
      # Code Climate setup & initialise
      - run:
          name: Code Climate test-reporter setup
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      # Testing configuration must be configured in package.json
      - run:
          name: Testing
          command: yarn test
      # Code Climate sending report
      - run:
          name: Code Climate report
          command: 
            ./cc-test-reporter after-build --coverage-input-type lcov --exit-code $?
  # ---------- Deployment job