

# Using CircleCI 2
version: 2

jobs: 
  build:
    docker: 
      # https://hub.docker.com/r/circleci/node/
      - image: circleci/node:11-browsers-legacy
    steps: 
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          keys:
          - learnzone-react-dependencies-{{ checksum "package.json" }}
          # [TODO] Fallback?
          - learnzone-react-dependencies-

      - run:
          name: install dependencies
          command: npm install

      - save_cache:
          key: learnzone-react-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules